### ISSUE TITLE
[ibm-telco] How to assign a role (master/worker) to nodes while deploying cluster using ztp playbooks

### ISSUE THREAD

**Issue by pmallan** [redhat-ztp/ztp-cluster-deploy#101]
@yrobla  is there a way to assign a role (master/worker) to nodes while deploying cluster using ztp playbooks?. It is possible in online AI tool. is it possible with ztp playbook? 

![image](https://user-images.githubusercontent.com/79190301/115188151-23f1fc80-a102-11eb-9c72-0c8ed42702e8.png)

As you see above master and worker role assigned to those master vms (edited)

**Comment by pmallan** [comment]
@yrobla master nodes playing both roles may have impact on deploying applications on the cluster. Master nodes are VMs with less resources. It would be good to master nodes role restricted to master only

**Comment by yrobla** [comment]
We assign masters a worker role becase they are needed by the internal openshift component. The typical and complete installation of OpenShift is 3  masters + 2 workers. As our use case is remote worker nodes, we just deploy with 3 masters, but then those need to get the worker label, in order to host some OpenShift workloads such as ingress.
But your "real" remote workers are also labelled as worker-du. So when you schedule some workload, you need to be sure that they are assigned to the worker-du label (not worker). If you do that, you will be sure that all the workloads needing a remote baremetal node will be assigned properly, and nothing will go by mistake on the controlplane.
